#pragma once

#include "Core/Common/Types/TimelineTypes.h"
#include <vector>
#include <string>

// Defines the types of automated actions the Director can perform.
enum class CommandType
{
	// Immediate camera switch to a specific player's perspective.
	Cut,

	// Modification of the Theater playback speed.
	SetSpeed
};

// An instruction generated by the Director to be executed during playback.
// Contains the 'what', 'when', and 'why' of an automated theater action.
struct DirectorCommand
{
	// The time within the replay when the command should trigger.
	float Timestamp{};

	// The nature of the action (e.g, switching cameras or changing speed).
	CommandType Type{};

	// The index and name of the player the Director decided to focus on.
	uint8_t TargetPlayerIdx{};
	std::string TargetPlayerName{};

	// The playback speed value (used if Type is SetSpeed).
	float SpeedValue{};

	// A summary of the Director's heuristic decision.
	// Format: "Score [X], Events[Y]", used for debug/UI.
	std::string Reason{};
};

// Represents a continuous window of high-interest gameplay.
// Created during the script generation by clustering events that involve
// the same player within a temporal look-ahead window.
struct ActionSegment
{
	// Collection of EventTypes that occurred within this segment's duration.
	std::vector<EventType> TotalEvents{};

	// The name and ID of the player this segment focuses on.
	std::string PlayerName{};
	uint8_t PlayerID{};

	// The aggregated weight of all events in this segment, determining its priority.
	int TotalScore{};

	// The calculated start and end times, including pre-roll and post-roll buffers.
	float StartTime{};
	float EndTime{};
};